### PR TITLE
Added support for proxy pass alias without a virtual host

### PR DESCRIPTION
**Pull request by lightglitch**
Previous discussion:

http://forums.pu-gh.com/viewtopic.php?f=2&t=238&start=0

### CODE REVIEW

**Comment by rodnaph** [comment]
This looks good - but one thing that it currently breaks is ajax calls from the javascript (which assume all URLs start at "/")

After this is fixed up I'd also like to have a more unified approach to creating these URLs.  Not sure if adding getUrl() to the properties object would be the wrong place to put it, but creating another object might mean a lot of work to get it injected everywhere...

**Comment by lightglitch** [comment]
I just saw that problem in ajax calls and the share action  is also not generating the correct paths.

And to have standard method to get the base url is really the best approach.

**Comment by rodnaph** [comment]
I'm not sure it's the _perfect_ solution, but it seems at least for now, Properties is the place to put this method (for Java and Javascript).  Something like...

<pre>
Properties.getUrl( '/file/images/image.png' ); // javascript
p.getUrl( '/json/search' ); // java
</pre>


So that'll need adding to...

<pre>
resources/htdocs/js/sockso.Properties.js
src/com/pugh/sockso/Properties.java
src/com/pugh/sockso/StringProperties.java
</pre>


Please make sure there are appropriate tests added for both these methods.

Does that sound ok?

**Comment by rodnaph** [comment]
As for the getUrlParam() method - this will just need to be adjusted so that any defined web root is removed.  so that way the current functionality will remain the same.  Again, there should be plenty of tests for that so just add to them to include this case.

**Comment by lightglitch** [comment]
Forget the getUrlParam problem the json bug was in other place.
If there are more bugs in json calls probably is something wrong in the ways the urls are built in the javascript files.

About the changes you mentioned I will do that as soon as I have the time and posted the update on this thread.

**Comment by rodnaph** [comment]
That's great!  Let me know if you need any help, otherwise I'll wait till ur done before I take another look.

Cheers.

**Comment by lightglitch** [comment]
I think is done now.
 I did some testing but I unable to run the tests because I don't have all the environment installed and configured so I will need your help on that part.

Please check it.
Cheers

**Comment by rodnaph** [comment]
Ok I'll check it out as soon as I can - but I'm really busy getting married and going on honeymoon so won't be for a few weeks sorry! :D

Thanks!

**Comment by lightglitch** [comment]
ok, no problem and congratulations.

**Comment by rodnaph** [comment]
Ok - this is now merged into master and will go out with the next release (probably 1.3).  Since you're the only person using this functionality at the moment just let me know if you find anything that's been missed and we can fixo upo.

Cheers for all your work on this!

**Comment by lightglitch** [comment]
thx

**Pull request merged**
