### PR TITLE
Automatic indexers for playlist

### PR DESCRIPTION
**Pull request by lightglitch**
What's it this pull request:

Support for playlists with relative paths
Support for multiple indexers to run
Implementation of a playlist indexer

It's missing the upgrade functions for sqlite and mysql and I'm not very happy with the DBCollectionManager handles the events of the different indexers.

But it's working, try it and let me know what you think.

### CODE REVIEW

**Comment by lightglitch** [comment]
And it's also missing fixing the current tests.

**Comment by rodnaph** [comment]
Wow, ok a lot of changes...  The fix for path concat, if you could move that to a separate pull request and add a test for it I'd be happy to merge it.  Same goes for the relative paths change too.

As for the last commit - that's the big one, and like you say the changes to CollectionManager I don't really want to accept as I've been trying to move stuff _out_ of there for a long time (i admit that class is not good :( ... ).  these changes are also missing unit tests.

If the indexer changes are going to get merged...

1) the collectionmanager changes need to go somewhere else (maybe needs a big new change splitting out all collectionmanager code to smaller classes)
2) tests added
3) remove duplication of code for switch between track/playlist indexer
4) change db field to be a smallint type instead of varchar which is fully qualified name.  an int will be much faster and smaller.

Don't worry about sqlite though, that was only an experiment and i'm going to remove support at some point.

**Comment by lightglitch** [comment]
1) I did think of refactoring the Collection Manager but the changes would be even greater and I didn't had the time for now.
2) I know
3) The is no duplication of code there because each one does different methods calls
4) which field are you talking about?

**Comment by rodnaph** [comment]
Yes there's no direct duplication but it would be much neater to handle the switching through polymorphism.

Db field I mean the one that has the fully qualified classname in it, be quicker to do this with an enum or int type?

**Pull request closed without merging**
