### PR TITLE
Add support for "Accept-Ranges" header so we can stream from arbitrary points in a track

### PR DESCRIPTION
**Pull request by nperrier**

### CODE REVIEW

**Comment by rodnaph** [comment]
Support for the Range header already exists, is there a bug in the implementation?  Looks like we're not setting the correct response headers possibly...  is that it?

One thing we can't do afaik is use the track on disk to check the content length we'll be returning as we could be transcoding to another bitrate...

**Comment by nperrier** [comment]
I did not consider the transcoder...where does that step happen?  Obviously if the file size is changed due to filtering through the transcoder, the byte counts will all be incorrect.

The problem I was trying to address was an issue with an old Android component (MediaPlayer) not playing very well with the server when streaming music.  The issue was likely more a problem with the MediaPlayer and not the server, but I did notice that Sockso was returning `Accept-Ranges: none` in the response header, which indicates that the server doesn't support range requests (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.5).  

This was my attempt to support the header.  If it's problematic, we can drop it, but if we can resolve the transcoder issue (basically getting correct byte counts if data is being transcoded) I'd like to get it in sockso.

**Comment by rodnaph** [comment]
You're right, we should definitely be advertising "Accept-Ranges".

The transcoding gets kicked off by the getMusicStream() method returning a MusicStream (which could be read from a file, or be the transcoded output from lame or whatever...).  We could only allow range requests when transcoding is not being used (in the default case) here...

https://github.com/rodnaph/sockso/blob/master/src/com/pugh/sockso/web/action/Streamer.java#L227

What do you think?

**Comment by nperrier** [comment]
Well, how would the client know if something is being transcoded or not?  If we advertise we support it, and the client expects it, but we pull the rug out because of a server-side setting, that might confuse the client.

In other words, I don't think we can advertise `Accept-Ranges: bytes` if it's only _conditionally_ supported.  

I could be wrong, there might be a way around this or it not be the case that HTTP strictly enforces this behavior.

**Comment by nperrier** [comment]
I may have misread your last response.  If we know ahead of time (which we do) that transcoding is on/off, we can tell the client it's supported.

I think that would be easy.  We just need to give the HttpResponse (and maybe MusicStreamer?) knowledge of the setting.

**Comment by rodnaph** [comment]
Yeah, that's exactly what I mean.  If we put contentLength information in _MusicStream_, that will be enough to determine that we can accept ranges.  We then just pass that to _sendTrackHeaders()_

:)

**Comment by nperrier** [comment]
Dumb question:  If transcoding is being used, and we cannot determine the total length of the content that is streaming, then isn't this a bug?:

https://github.com/rodnaph/sockso/blob/master/src/com/pugh/sockso/web/action/Streamer.java#L318

**Comment by rodnaph** [comment]
Yeah that will be incorrect for transcoded streams, and could explain a bug a few people have been seeing where the track finishes playing too early.  Your work should sort all this out though :)

**Comment by nperrier** [comment]
I'm not sure what to send for `Content-Length` if we can't determine the value.

I looked up how to handle this on various blogs and forums.  We could use `Transfer-Encoding: chunked`, but that requires we advertise `HTTP 1.1` and I think we currently send `HTTP 1.0`

http://en.wikipedia.org/wiki/Chunked_transfer_encoding

What do you think?

**Comment by rodnaph** [comment]
I think that would be fine, as long as we send the "Connection: close" header too.

**Comment by nperrier** [comment]
Alright, review time Rod!

I haven't written tests yet.  Nor have I been able to test the ChunkedStream.  I can't seem to get the encoders to work on my windows box.  I'm following the instructions from the website manual (http://sockso.pu-gh.com/manual/encoders.html) but it just kinda hangs when I attempt to stream (only tested an mp4 -> mp3 so far).

**Comment by nperrier** [comment]
Did you want a chance to review these changes before I merge them Rod?

**Comment by rodnaph** [comment]
No, don't have time to test it out, but it looks fine.  :)

**Pull request merged**
