### PR TITLE
Updated coverer plugins

### PR DESCRIPTION
**Pull request by nperrier**
Please ignore the latest commit, it's just whitespace fixes.

The commit of interest is the penultimate one:

https://github.com/nperrier/sockso/commit/71558638389882032995b2e94495510a7b802198

### CODE REVIEW

**Comment by rodnaph** [comment]
Oh and lots of whitespace changes... :-/

**Comment by rodnaph** [comment]
Further to using the Cache interface - you could extend this new TimedCache class...

https://github.com/rodnaph/sockso/commit/18fee9bf21a819b521fd20d4474778fdd435bfed

With a FileCache implementation, and use that for the cover cache.

**Comment by nperrier** [comment]
Have you looked into using a WeakHashMap instead of HashMap for the ObjectCache?

See http://stackoverflow.com/questions/154724/when-would-you-use-a-weakhashmap-or-a-weakreference

**Comment by nperrier** [comment]
I'm trying to understand what your thinking is here for the refactor: 

Rename CoverArtCache -> FileCache and extend TimedCache instead of implementing ImageCache?

So the TimedCache is an "in memory" cache, in that, the image data should not be cached on the file system anymore?  Or do you mean to leave the file system cache alone and supplement it with a faster in memory cache that has an expiration?

**Comment by nperrier** [comment]
I see the point of putting the images in memory, as reading from disk is expensive and it might make the cover art quite a bit snappier on the client side.  Just trying to figure out how to separate file system caching and in memory caching...

**Comment by rodnaph** [comment]
No, sorry I should have explained a bit more.  The TimedCache is an abstract class that just requires implementing readRaw() and writeRaw() for data storage.  This is then extended by ObjectCache that uses a simple HashMap to provide an in-memory cache.

What you can do is create a another class called CoverArtCache that extends TimedCache, and just implements readRaw() and writeRaw() and what you can do here is read/write the images to/from the file system.  So you get all the benefits of TimedCache, and the same interface via Cache. (i said FileCache to be more generic, but it might make sense for now to call it CoverArtCache)

Does that make sense?

I haven't heard of the WeakHashMap no - I'll take a look thanks!

**Comment by nperrier** [comment]
OK, I thought you were trying to create a hybrid cache class for the coverart that read/writes to the file system and also keeps the images in memory...I was a bit confused how that would work :)

**Comment by nperrier** [comment]
I would assume I need to extend CoverArt from CachedObject now?  If I move the code from getCoverArt() to readRaw(), then call readRaw() from the body of getCoverArt(), since getCoverArt() returns a CoverArt, I can't covert a CachedObject (which readRaw() returns) to a CoverArt object, correct?

Trying to imagine what your idea was for implementing this correctly...

**Comment by nperrier** [comment]
Nevermind, I just realized CachedObject.getValue() is for that very purpose.

**Comment by nperrier** [comment]
Should TimedCache.readRaw()/writeRaw() throw IOException's?  The problem I'm running into is that the CoverArtCache needs to do IO to read/write images, but doing that could cause an IOException to be raised.  If I implement this in the read/writeRaw ops, I can't re-throw it up the stack - the only option I see is returning a null CachedObject or an empty one. (see TODO's)

Thoughts?

**Comment by rodnaph** [comment]
Ah yes I didn't think of Exception's - yes please just alter the interface so those methods throw Exceptions (because it might not just be IOExceptions that implementors need to throw).

**Comment by nperrier** [comment]
Is that a good idea?  Now methods of ObjectCache throw Exceptions unnecessarily (since it extends TimedCached which implements Cache interface) and require client code to catch them.  I think maybe the Cache interface is a bit too generic for both the CoverArtCache (which throws IOExceptions) and an ObjectCache (which throws nothing).

**Comment by rodnaph** [comment]
Yeah don't worry about it, throwing exceptions is fine!  :)

**Comment by nperrier** [comment]
I decided a CacheException class would be best rather than throw Exception everywhere.  Let me know what you think.

**Comment by nperrier** [comment]
What do you think about adding auth token functionality for mobile apps to the api (see soundcloud doc for example: http://developers.soundcloud.com/docs/api/authentication#authorization-code-flow)

Currently, the only way to do this is via a cookie, which is kinda awkward to program on android :\

**Comment by rodnaph** [comment]
Hmm...  Not sure about token auth, maybe...  but we can deal with that in a separate pull request.

Is this cache feature complete now then?  I'll check it out later and pull it to master if it's done.

**Comment by nperrier** [comment]
Yes, it's completed and all tests passed.

**Comment by rodnaph** [comment]
Ok I've merged this to master now, thanks!

Few things I noticed when merging though, firstly all the whitespace changes - I think these were introduced ages ago so maybe not to worry about now.  But I had to manually unstage them all before commit (git reset -p).  If your IDE keeps doing this then you can use interactive add to make sure they don't get committed (git add -i).

Also, I always make variables final (unless impossible), this just keeps me on top of reducing mutation as much as possible, and usually results in cleaner less buggy code I find.

Looking forward to your token auth pull request ;)

**Comment by nperrier** [comment]
Arrrgh, I thought I fixed the whitespace issues!

**Pull request closed without merging**
