### PR TITLE
Importing/deleting multiple playlists + directory persistence

### PR DESCRIPTION
**Pull request by davis-junior**
Added support for:
- importing/deleting multiple playlists
- directory persistence

### CODE REVIEW

**Comment by rodnaph** [comment]
Looks good, if you could fix the problem with the whole locale file getting
marked as changed that would be good (probably line endings?) - I'll try and
do a final review and merge soon.

**Comment by davis-junior** [comment]
Hmm, I reverted the commits but doing so closed the pull request automatically. I'm also having trouble with the commits being removed completely. I'll work on it later tonight.

**Comment by davis-junior** [comment]
Ok, I fixed everything just by recreating the fork. But since I cannot reopen this pull request, I must have to recreate one. I would like to prevent this in the future. How would I reset my commits without the pull requests being closed?

**Comment by rodnaph** [comment]
Yes, I can't see any pull requests open at the moment from you so please
open a new one.  Thanks!

**Pull request merged**
